[package]
name = "mpf"
version = "0.1.0"
authors = ["John Peel <john@dgby.org>"]
edition = "2021"
repository = "https://github.com/JohnPeel/repkg"
license = "MIT"

[dependencies]
binrw = "*"
common = { path = "../common" }
