[package]
name = "dds"
version = "0.1.0"
authors = ["John Peel <john@dgby.org>"]
edition = "2018"
repository = "https://github.com/JohnPeel/repkg"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bitflags = "1.3"
